version: '3.4'

services:
  assetrental.api:
    image: ${DOCKER_REGISTRY-}assetrentalapi
    build:
      context: .
      dockerfile: AssetRental.API/Dockerfile
    ports:
        - 54321:80  
    depends_on: 
        - db 
        - rabbitmq
  db: 
    container_name: assetrental_db
    image: postgres:latest
    environment:
        POSTGRES_PASSWORD: "your_password"
        POSTGRES_USER: "your_username"
        POSTGRES_DB: "your_database_name"
    ports:
        - "1433:1433"
  rabbitmq:
    container_name: assetrental_rabbitmq
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
        - "5672:5672"
        - "15673:15673"
    expose:
        - 5672   
        - 15761  
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest